[package]
name = "concurrency-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
libc = "0.2.175"
mio = { version = "1.0.4", features = ["net", "os-poll"] }
tokio = { version = "1.47.1", features = ["full"] }
